GET http://211.63.24.41:8080/view/victory/job/talk-api-mocha/job/master/lastBuild/api/json?pretty=true
Authorization: Basic xxx

###


###
GET http://211.63.24.41:8080/view/victory/job/talk-api-mocha/job/master/api/json?pretty=true

###
GET http://211.63.24.41:8080/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken

###
GET https://victory-portal.spectra.co.kr/wp-json/wp/v2/posts?per_page=1
Authorization: Basic xx
###

